# Generated by Django 4.1.1 on 2022-09-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_name_student_face_encoding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
