# Generated by Django 4.1.1 on 2022-09-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_name'),
        ('students', '0003_alter_student_student_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(null=True, to='teachers.course'),
        ),
    ]
