# Generated by Django 4.1.1 on 2022-09-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
